BenchConstants = {
  BENCHES_RECEIVED: "BENCHES_RECEIVED",
  BENCH_CREATED: "BENCH_CREATED",
  FILTERS_RECEIVED: "FILTERS_RECEIVED",
  NEW_SELECTED_MARKER: "NEW_SELECTED_MARKER"
};

module.exports = BenchConstants;
